name: CI/CD Pipeline for Advanced Tic-Tac-Toe

# Add permissions for the workflow
permissions:
  contents: write  # Required for creating releases

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt 6 and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-tools-dev build-essential

    - name: List directory contents
      working-directory: ./project
      run: ls -la

    - name: Build the project
      working-directory: ./project
      run: |
        qmake6 TicTacToe_With_Tests.pro  # Adjust .pro file name if needed
        make

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt 6 and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-tools-dev build-essential

    - name: Build the project with tests
      working-directory: ./project
      run: |
        qmake6 TicTacToe_With_Tests.pro CONFIG+=test
        make

    - name: Run unit tests
      working-directory: ./project
      run: |
        ./TicTacToeTests  # Update this if the test executable name differs

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'  # Only deploy on push to main

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt 6 and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-tools-dev build-essential

    - name: Build the project
      working-directory: ./project
      run: |
        qmake6 TicTacToe_With_Tests.pro
        make

    - name: Package the binary
      working-directory: ./project
      run: |
        mkdir -p release
        cp TicTacToe_With_Tests release/  # Adjust executable name if different
        tar -czvf tictactoe-${{ github.sha }}.tar.gz -C release TicTacToe_With_Tests

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: release-${{ github.sha }}
        name: Release ${{ github.sha }}
        draft: false
        prerelease: false
        files: ./project/tictactoe-${{ github.sha }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        files: ./project/tictactoe-${{ github.sha }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
